In [1]:
import numpy as np
# 원본 영화 평점 데이터
A = np.array([[4, 1, 5, 4, 1],
              [2, 3, 5, 2, 3],
              [1, 3, 4, 1, 3],
              [2, 2, 4, 2, 2],
              [1, 3, 4, 1, 3]])

In [2]:
# 두 개의 인수분해 행렬 구해보기

array1 = np.array([[4, 1],
                   [2, 3],
                   [1, 3],
                   [2, 2],
                   [1, 3]])

array2 = np.array([[1, 0, 1, 1, 0],
                   [0, 1, 1, 0, 1]])

In [3]:
array1.shape, array2.shape

((5, 2), (2, 5))

In [4]:
array1 @ array2

array([[4, 1, 5, 4, 1],
       [2, 3, 5, 2, 3],
       [1, 3, 4, 1, 3],
       [2, 2, 4, 2, 2],
       [1, 3, 4, 1, 3]])

## 값을 모르게
- 누락값이 있는 부분을 맞추는 것

In [5]:
A = np.array([[4, 1, 5, np.nan, 1],
              [2, 3, np.nan, 2, 3],
              [1, np.nan, 4, 1, 3],
              [np.nan, 2, 4, np.nan, 2],
              [1, np.nan, 4, 1, 3]])
A

array([[ 4.,  1.,  5., nan,  1.],
       [ 2.,  3., nan,  2.,  3.],
       [ 1., nan,  4.,  1.,  3.],
       [nan,  2.,  4., nan,  2.],
       [ 1., nan,  4.,  1.,  3.]])

In [6]:
mask = ~np.isnan(A)
mask

array([[ True,  True,  True, False,  True],
       [ True,  True, False,  True,  True],
       [ True, False,  True,  True,  True],
       [False,  True,  True, False,  True],
       [ True, False,  True,  True,  True]])

In [14]:
# U = 5 * ?
# V = ? * 5
# ?가 커질 수록 파라미터 수가 많아진다.

In [7]:
k = 2
m, n = A.shape

# 아무 값을 줘놓고 경사하강법을 통해 수렴해 나갈 것임.
U = np.random.rand(m, k)
V = np.random.rand(n, k)  # k행 n열이 맞음. 계산을 위해 이렇게 표현

U @ V.T

array([[0.446511  , 0.52248256, 0.45030764, 0.61159577, 0.23230067],
       [0.78933263, 0.37503343, 0.29753689, 0.85021192, 0.13698104],
       [0.16352244, 0.16894861, 0.14456154, 0.21455164, 0.07390111],
       [0.7284995 , 0.29950113, 0.23223486, 0.76505671, 0.10316274],
       [0.48522432, 0.47931577, 0.40896109, 0.6273787 , 0.20830884]])

In [8]:
lr = 0.01  # 학습률

for i in range(5000):
    A_pred = U @ V.T

    # 오차마스크
    E = np.zeros((m, n))
    E[mask] = A_pred[mask] - A[mask]  # True인 부분만 접근한다.

    U_grad = E @ V
    V_grad = E.T @ U

    U -= U_grad * lr
    V -= V_grad * lr

    loss = sum(E[mask] **2)
    print(loss)

118.54119207039282
113.20498139156037
107.26200464402885
100.71730436894424
93.6120183736473
86.03028279081052
78.10268696226932
70.0039852072141
61.94327705753082
54.14630879907797
46.83178969418168
40.185982424051254
34.34124225725286
29.36369914740932
25.252771188777103
21.951634656616577
19.364746169638014
17.377265012653965
15.871958027771319
14.741106444825466
13.89297914863258
13.253832790819345
12.76695285825411
12.390170360088456
12.092906134942275
11.853368351536457
11.656191282415497
11.490587616731435
11.34897341882824
11.22598032143415
11.117763380283197
11.021524365841314
10.93518705447074
10.857177379443595
10.786274820339584
10.721511715119927
10.662104636620908
10.607407187989432
10.556877129980752
10.510053142869047
10.466538113355144
10.425986884485015
10.388097095556933
10.352602191835773
10.319265982104458
10.2878783192737
10.258251610457792
10.230217950888107
10.203626735572639
10.17834264334077
10.1542439161047
10.131220875928065
10.109174636520672
10.08801597587

In [35]:
A_pred

array([[3.99998978, 0.99999931, 5.00000381, 3.99948658, 0.99999904],
       [2.00004868, 2.99999931, 5.00007428, 1.99995441, 2.99999988],
       [0.99997654, 2.99999898, 4.00000003, 1.00002382, 2.99999969],
       [1.99997716, 2.00000157, 3.99999745, 1.99981996, 2.00000186],
       [0.99997654, 2.99999898, 4.00000003, 1.00002382, 2.99999969]])

In [36]:
# nan값을 경사하강법을 통한 예측값을 통해 채우기
A_filled = A.copy()

A_filled[~mask] = A_pred[~mask]
A_filled

array([[4.        , 1.        , 5.        , 3.99948658, 1.        ],
       [2.        , 3.        , 5.00007428, 2.        , 3.        ],
       [1.        , 2.99999898, 4.        , 1.        , 3.        ],
       [1.99997716, 2.        , 4.        , 1.99981996, 2.        ],
       [1.        , 2.99999898, 4.        , 1.        , 3.        ]])

In [39]:
# 컴퓨터가 예측해준 값들만 넣어 둠.
zeros = np.zeros(A_pred.shape)
zeros[~mask] += A_pred[~mask]
zeros

array([[0.        , 0.        , 0.        , 3.99948658, 0.        ],
       [0.        , 0.        , 5.00007428, 0.        , 0.        ],
       [0.        , 2.99999898, 0.        , 0.        , 0.        ],
       [1.99997716, 0.        , 0.        , 1.99981996, 0.        ],
       [0.        , 2.99999898, 0.        , 0.        , 0.        ]])

In [42]:
for i in range(len(zeros)):
    a = zeros[i]
    for j in range(len(a)):
        if a[j] >= 4:
            print(f"{i}번째 유저, {j}번째 영화 추천!")

1번째 유저, 2번째 영화 추천!
